/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadsRouteImport } from './routes/uploads'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PreferencesRouteImport } from './routes/preferences'
import { Route as HomeRouteImport } from './routes/home'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KnowledgeSetsIndexRouteImport } from './routes/knowledge-sets/index'
import { Route as KnowledgeBasesIndexRouteImport } from './routes/knowledge-bases/index'
import { Route as DocumentsIndexRouteImport } from './routes/documents/index'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as KnowledgeSetsKnowledgeSetIdRouteImport } from './routes/knowledge-sets/$knowledgeSetId'
import { Route as KnowledgeBasesKnowledgeBaseIdRouteImport } from './routes/knowledge-bases/$knowledgeBaseId'
import { Route as DocumentsDocumentIdRouteImport } from './routes/documents/$documentId'
import { Route as ChatSessionIdRouteImport } from './routes/chat/$sessionId'

const UploadsRoute = UploadsRouteImport.update({
  id: '/uploads',
  path: '/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesRoute = PreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeSetsIndexRoute = KnowledgeSetsIndexRouteImport.update({
  id: '/knowledge-sets/',
  path: '/knowledge-sets/',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeBasesIndexRoute = KnowledgeBasesIndexRouteImport.update({
  id: '/knowledge-bases/',
  path: '/knowledge-bases/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsIndexRoute = DocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeSetsKnowledgeSetIdRoute =
  KnowledgeSetsKnowledgeSetIdRouteImport.update({
    id: '/knowledge-sets/$knowledgeSetId',
    path: '/knowledge-sets/$knowledgeSetId',
    getParentRoute: () => rootRouteImport,
  } as any)
const KnowledgeBasesKnowledgeBaseIdRoute =
  KnowledgeBasesKnowledgeBaseIdRouteImport.update({
    id: '/knowledge-bases/$knowledgeBaseId',
    path: '/knowledge-bases/$knowledgeBaseId',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocumentsDocumentIdRoute = DocumentsDocumentIdRouteImport.update({
  id: '/documents/$documentId',
  path: '/documents/$documentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatSessionIdRoute = ChatSessionIdRouteImport.update({
  id: '/chat/$sessionId',
  path: '/chat/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/preferences': typeof PreferencesRoute
  '/profile': typeof ProfileRoute
  '/uploads': typeof UploadsRoute
  '/chat/$sessionId': typeof ChatSessionIdRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/knowledge-bases/$knowledgeBaseId': typeof KnowledgeBasesKnowledgeBaseIdRoute
  '/knowledge-sets/$knowledgeSetId': typeof KnowledgeSetsKnowledgeSetIdRoute
  '/chat/': typeof ChatIndexRoute
  '/documents/': typeof DocumentsIndexRoute
  '/knowledge-bases/': typeof KnowledgeBasesIndexRoute
  '/knowledge-sets/': typeof KnowledgeSetsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/preferences': typeof PreferencesRoute
  '/profile': typeof ProfileRoute
  '/uploads': typeof UploadsRoute
  '/chat/$sessionId': typeof ChatSessionIdRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/knowledge-bases/$knowledgeBaseId': typeof KnowledgeBasesKnowledgeBaseIdRoute
  '/knowledge-sets/$knowledgeSetId': typeof KnowledgeSetsKnowledgeSetIdRoute
  '/chat': typeof ChatIndexRoute
  '/documents': typeof DocumentsIndexRoute
  '/knowledge-bases': typeof KnowledgeBasesIndexRoute
  '/knowledge-sets': typeof KnowledgeSetsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/preferences': typeof PreferencesRoute
  '/profile': typeof ProfileRoute
  '/uploads': typeof UploadsRoute
  '/chat/$sessionId': typeof ChatSessionIdRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/knowledge-bases/$knowledgeBaseId': typeof KnowledgeBasesKnowledgeBaseIdRoute
  '/knowledge-sets/$knowledgeSetId': typeof KnowledgeSetsKnowledgeSetIdRoute
  '/chat/': typeof ChatIndexRoute
  '/documents/': typeof DocumentsIndexRoute
  '/knowledge-bases/': typeof KnowledgeBasesIndexRoute
  '/knowledge-sets/': typeof KnowledgeSetsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/preferences'
    | '/profile'
    | '/uploads'
    | '/chat/$sessionId'
    | '/documents/$documentId'
    | '/knowledge-bases/$knowledgeBaseId'
    | '/knowledge-sets/$knowledgeSetId'
    | '/chat/'
    | '/documents/'
    | '/knowledge-bases/'
    | '/knowledge-sets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/preferences'
    | '/profile'
    | '/uploads'
    | '/chat/$sessionId'
    | '/documents/$documentId'
    | '/knowledge-bases/$knowledgeBaseId'
    | '/knowledge-sets/$knowledgeSetId'
    | '/chat'
    | '/documents'
    | '/knowledge-bases'
    | '/knowledge-sets'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/preferences'
    | '/profile'
    | '/uploads'
    | '/chat/$sessionId'
    | '/documents/$documentId'
    | '/knowledge-bases/$knowledgeBaseId'
    | '/knowledge-sets/$knowledgeSetId'
    | '/chat/'
    | '/documents/'
    | '/knowledge-bases/'
    | '/knowledge-sets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  PreferencesRoute: typeof PreferencesRoute
  ProfileRoute: typeof ProfileRoute
  UploadsRoute: typeof UploadsRoute
  ChatSessionIdRoute: typeof ChatSessionIdRoute
  DocumentsDocumentIdRoute: typeof DocumentsDocumentIdRoute
  KnowledgeBasesKnowledgeBaseIdRoute: typeof KnowledgeBasesKnowledgeBaseIdRoute
  KnowledgeSetsKnowledgeSetIdRoute: typeof KnowledgeSetsKnowledgeSetIdRoute
  ChatIndexRoute: typeof ChatIndexRoute
  DocumentsIndexRoute: typeof DocumentsIndexRoute
  KnowledgeBasesIndexRoute: typeof KnowledgeBasesIndexRoute
  KnowledgeSetsIndexRoute: typeof KnowledgeSetsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uploads': {
      id: '/uploads'
      path: '/uploads'
      fullPath: '/uploads'
      preLoaderRoute: typeof UploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences': {
      id: '/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof PreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-sets/': {
      id: '/knowledge-sets/'
      path: '/knowledge-sets'
      fullPath: '/knowledge-sets/'
      preLoaderRoute: typeof KnowledgeSetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-bases/': {
      id: '/knowledge-bases/'
      path: '/knowledge-bases'
      fullPath: '/knowledge-bases/'
      preLoaderRoute: typeof KnowledgeBasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/': {
      id: '/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof DocumentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-sets/$knowledgeSetId': {
      id: '/knowledge-sets/$knowledgeSetId'
      path: '/knowledge-sets/$knowledgeSetId'
      fullPath: '/knowledge-sets/$knowledgeSetId'
      preLoaderRoute: typeof KnowledgeSetsKnowledgeSetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-bases/$knowledgeBaseId': {
      id: '/knowledge-bases/$knowledgeBaseId'
      path: '/knowledge-bases/$knowledgeBaseId'
      fullPath: '/knowledge-bases/$knowledgeBaseId'
      preLoaderRoute: typeof KnowledgeBasesKnowledgeBaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/$documentId': {
      id: '/documents/$documentId'
      path: '/documents/$documentId'
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof DocumentsDocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$sessionId': {
      id: '/chat/$sessionId'
      path: '/chat/$sessionId'
      fullPath: '/chat/$sessionId'
      preLoaderRoute: typeof ChatSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  PreferencesRoute: PreferencesRoute,
  ProfileRoute: ProfileRoute,
  UploadsRoute: UploadsRoute,
  ChatSessionIdRoute: ChatSessionIdRoute,
  DocumentsDocumentIdRoute: DocumentsDocumentIdRoute,
  KnowledgeBasesKnowledgeBaseIdRoute: KnowledgeBasesKnowledgeBaseIdRoute,
  KnowledgeSetsKnowledgeSetIdRoute: KnowledgeSetsKnowledgeSetIdRoute,
  ChatIndexRoute: ChatIndexRoute,
  DocumentsIndexRoute: DocumentsIndexRoute,
  KnowledgeBasesIndexRoute: KnowledgeBasesIndexRoute,
  KnowledgeSetsIndexRoute: KnowledgeSetsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
